name: CI/CD for CV NN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-train:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting and formatting checks
        run: |
          pip install black flake8
          black --check .
          flake8 .

      - name: Run unit tests
        run: |
          pytest tests/

      - name: Train the model
        run: |
          python src/train.py
        if: github.event_name == 'push'

      - name: Save trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/

  deploy:
    needs: test-and-train
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: models/

      - name: Build and push Docker image
        run: |
          docker build -t my-cv-model:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-cv-model:latest mydockerhubuser/my-cv-model:latest
          docker push mydockerhubuser/my-cv-model:latest
