name: CI/CD for CV NN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      TRAIN_MODEL:
        description: "Train a new model?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  test-and-train:
    runs-on: ubuntu-22.04

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting and formatting checks
        run: |
          pip install black flake8
          black .
          flake8 .

      - name: Run unit tests
        run: |
          pytest tests/

      - name: Train the model
        if: github.event_name == 'push' || github.event.inputs.TRAIN_MODEL == 'true'
        run: |
          python src/train.py

      - name: Save trained model
        if: github.event.inputs.TRAIN_MODEL == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/
